clc;
clear all;
close all;
x = imread('brain.jpg');
y = imread('fundus.jpg');
y = rgb2gray(y);
y = imresize(y,[100,100])
subplot(231);
imshow(x);
title('Original Image');
x = rgb2gray(x);
x = imresize(x,[100,100]);
subplot(232);
imshow(x);
title('Grayscale Image');
r = x+y;
subplot(233);
imshow(y);
title('Addition');
z = x-y;
subplot(234);
imshow(z);
title('Subtraction');
p = x.*y;
subplot(235);
imshow(p);
title('Multiplication');
q = x./y;
subplot(236);
imshow(q);
title('Division');