clc;
clear all;
close all;
a=imread('mri.jpg');
b=rgb2gray(a); 
subplot(331);
imshow(b,copper); 
title('COPPER');
subplot(332);
rgbplot(copper);
title('RGB PLOT 1');
subplot(333);
imshow(b,spring(80));
title('COLOUR MAPPED IMAGE');
subplot(334);
rgbplot(spring(80));
title('RGB PLOT 2');
subplot(335);
imshow(b,summer); 
title('SUMMER'); 
subplot(336); 
rgbplot(summer); 
title('RGB PLOT 3');
