clc;
clear all;
close all;
x = imread('brain.jpg');
y = strel('disk',10);
subplot(321);
imshow(x);
title('Original Image');
z = imdilate(x,y);
subplot(322);
imshow(z);
title('Dilation');
p = imerode(x,y);
subplot(323);
imshow(p);
title('Erosion');
q = imopen(x,y);
subplot(324);
imshow(q);
title('Opening');
r = imclose(x,y);
subplot(325);
imshow(r);
title('Closing');