clc;
clear all;
close all;
x = imread('brain.jpg');
x = rgb2gray(x);
subplot(231);
imshow(x);
title('input image');
canny = edge(x, 'canny');
subplot(232);
imshow(canny);
title('canny edge detection');
level = graythresh(x);
otsu = imbinarize(x, level);
subplot(233);
imshow(otsu);
title('otsu edge detection');
prewitts = fspecial('prewitt');
prewittsi = imfilter(x,prewitts);
subplot(234);
imshow(prewittsi);
title('prewitt edge detection');
sobels = fspecial('sobel');
sobelsi = imfilter(x, sobels);
subplot(235);
imshow(sobelsi);
title('sobel edge detection');
r = fspecial('roberts');
robertsi = imfilter(x, r);
subplot(236);
imshow(robertsi);
title('robert edge detection');