clc;
clear all;
close all;
a=imread('mri.jpg');
a(:,:,2)=0;
a(:,:,3)=0;
subplot(221);
imshow(a);
title('Red comp');
b=imread('mri.jpg');
b(:,:,1)=0;
b(:,:,3)=0;
subplot(222);
imshow(b);
title('Blue comp');
c=imread('mri.jpg');
c(:,:,1)=0;
c(:,:,2)=0;
subplot(223);
imshow(c);
title('Green comp');
a=imread('mri.jpg');
R=a(:,:,1);
G=a(:,:,2);
B=a(:,:,3);
new= cat(3,R,G,B); 
subplot(224); imshow(new); 
title('rgb image');
