clc;
clear all;
close all;
x = double(rgb2gray(imread('brain.jpg')));
y = fft2(x);
y = (fftshift(y));
subplot(341);
imshow(uint8(x));
title('Grayscale Image');
temp = log(abs(y));
subplot(342);
imshow(temp,[]);
title('Fourier Spectra');
[M,N] = size(x);
u = 0:(M-1);
v = 0:(N-1);
idx = find(u > M/2);
u(idx) = u(idx) - M;
idy = find(v > N/2);
v(idy) = v(idy) - N;
[V,U] = meshgrid(v,u);
D0 = 30;
D = sqrt(U.^2+V.^2);
H = ifftshift(double(D<=D0));
g = real(ifft2(H.*y));
subplot(343);
imshow(uint8(abs(g)));
title('Filtered Image');
subplot(344);
imshow(H,[]);
title('Ideal Low Pass Filter');
Hg = ifftshift(exp(-(D.^2)./(2*(D0.^2))));
g = real(ifft2(Hg.*y));
subplot(345);
imshow(uint8(abs(g)));
title('Filtered Image');
subplot(346);
imshow(Hg,[]);
title('Gaussian Loww Pass Filter');
D0 = 10;
H = ifftshift(double(D<=D0));
Hp = 1-H;
g = real(ifft2(Hp.*y));
subplot(347);
imshow(uint8(abs(g)));
title('Filtered Image');
subplot(348);
imshow(Hp,[]);
title('Ideal Low Pass Fiter');
D0 = 10;
H = ifftshift(exp(-(D.^2)./(2*(D0.^2))));
Hgh = 1 - H;
g = real(ifft2(Hgh.*y));
subplot(349);
imshow(uint8(abs(g)));
title('Filtered Image');
subplot(3,4,10);
imshow(Hgh,[]);
title('Gaussian High Pass Filter');