clc;
clear all;
close all;
x = imread('brain.jpg');
subplot(221);
imshow(x);
title('Brain Image');
x = double(rgb2gray(imread('brain.jpg')));
y = fft2(x);
y1 = fftshift(y);
subplot(222);
imshow(x);
title('Original Image');
temp = log(abs(y));
subplot(223);
imshow(temp,[]);
title('Log Transformation - I');
temp2 = log(abs(y1));
subplot(224);
imshow(temp2,[-1 15]);
colormap("jet");
colorbar;
title('Log Transformation - II');