clc;
clear all;
close all;
a = imread('brain.jpg');
subplot(231);
imshow(a);
title('Original Image');
b = rgb2gray(a);
subplot(232);
imshow(b);
title('Grayscale Image');
g = [0 1 0;1 -2 1;0 1 0];
x = imfilter(b, g);
subplot(233);
imshow(x);
title('Laplacian Filter');
x = imsharpen(b);
subplot(234);
imshow(x);
title('Unsharp Image');
y = im2double(a);
x = rgb2gray(y);
hx = [1 0;0 -1];
hy = [0 1;-1 0];
p = imfilter(x,hx);
q = imfilter(x,hy);
r = sqrt(p.^2+q.^2);
subplot(235);
imshow(r);
title('Robert Gradient');
t = [1 2 1;0 0 0;1 -2 -1];
x = imfilter(b, t);
subplot(236);
imshow(x);
title('Sobel Operator');