clc;
clear all;
close all;
x = imread('mri.jpg');
x = imresize(x,[100,100]);
y = imread('mrit.jpg');
y = imresize(y,[100,100]);
subplot(331);
imshow(x);
title('Healthy Brain');
subplot(332);
imhist(x);
title('Histogram');
subplot(333);
imshow(y);
title('Tumor Brain');
subplot(334);
imhist(y);
title('Histogram');
Ix = histeq(x);
Iy = histeq(y);
subplot(335);
imshow(Ix);
title('Healthy Brain');
subplot(336);
imhist(Ix);
title('Histogram');
subplot(337);
imshow(Iy);
title('Healthy Brain');
subplot(338);
imhist(Iy);
title('Histogram');
z = imhistmatch(x,y);
subplot(339);
imshow(z);
title('Histogram Matching');
