clc;
clear all;
close all;
x = imread('brain.jpg');
subplot(231);
imshow(x);
title('Original Image');
x = rgb2gray(x);
subplot(232);
imshow(x);
title('Grayscale Image');
g = fspecial('average');
d = filter2(g,x)/255;
subplot(233);
imshow(d);
title('Standard Averaging Filter');
y = imfilter(x, g);
subplot(234);
imshow(y);
title('Weighted Averaging Filter');
e = fspecial('gaussian',[1,1]);
subplot(235);
y = filter2(e, y)/255;
imshow(y);
title('Gaussian Filter');
