clc;
clear all;
close all;
x = imread('brain.jpg');
subplot(231);
imshow(x);
title('Original Image');
x = rgb2gray(x);
subplot(232);
imshow(x);
title('Grayscale Image');
x = imnoise(x, 'salt & pepper', 0.09);
subplot(233);
imshow(x);
title('Salt and Pepper');
x = medfilt2(x);
subplot(234);
imshow(x);
title('Median Filter');
x = ordfilt2(x,9,ones(3,3));
subplot(235);
imshow(x);
title('Maximum Filter');
x = ordfilt2(x, 1, ones(3,3));
subplot(236);
imshow(x);
title('Minimum Filter');