clc;
clear all;
close all;
x = rgb2gray(imread("mri.jpg"));
subplot(431);
imshow(x);
title('Identity Transform');
subplot(432);
imhist(x);
title('Histogram');
y = imcomplement(x);
subplot(433);
imshow(y);
title('Negative');
subplot(434);
imhist(y);
title('Histogram');
l = 2*log(1+double(y));
lt = im2uint8(mat2gray(l));
subplot(435);
imshow(lt);
title('Log Transform');
subplot(436);
imhist(lt);
title('Histogram');
z = imcomplement(lt);
subplot(437);
imshow(z);
title('Inverse Log');
subplot(438);
imhist(z);
title('Histogram');
q = imadjust(y,[0 1],[1 0],1.5)
subplot(439);
imshow(q);
title('Power Law');
subplot(4,3,10);
imhist(q);
title('Histogram');
r = 1./(1+(1./(double(y)+eps)).^0.10);
subplot(4,3,11);
imshow(r);
title('Contrast Stretching');
subplot(4,3,12);
imhist(r);
title('Histogram');
