clc;
clear all;
close all;
x = double(rgb2gray(imread('brain.jpg')));
subplot(431);
imshow(uint8(x));
title('Original Image');
y = fft2(x);
y = fftshift(y);
temp = log(abs(y));
subplot(432);
imshow(temp,[]);
title('Fourier Spectra');
[M N] = size(x);
u = 0:(M-1);
v = 0:(N-1);
idx = find(u>M/2);
u(idx) = u(idx)-M;
idy = find(v>N/2);
v(idy) = v(idy)-N;
[V U] = meshgrid(v,u);
D0 = 30;
D = sqrt(U.^2+V.^2);
H = ifftshift(double(D<=D0));
g = real(ifft2(H.*y));
subplot(433);
imshow(uint8(abs(g)));
title('Filtered Image');
subplot(434);
imshow(H,[]);
title('Ideal Lowpass Filter');
Hg = ifftshift(exp(-(D.^2)./(2.*(D0.^2))));
g = real(ifft2(Hg.*y));
subplot(435);
imshow(uint8(abs(g)));
title('Filtered Image');
subplot(436);
imshow(Hg,[]);
title('Gaussian Lowpass Filter');
D0 = 10;
H = ifftshift(double(D<=D0));
Hp = 1-H;
g = real(ifft2(Hp.*y));
subplot(437);
imshow(uint8(abs(g)));
title('Filtereed Image');
subplot(438);
imshow(Hp,[]);
title('Ideal Highpass Filter');
H = ifftshift(exp(-(D.^2)./(2.*(D0.^2))));
Hgh = 1-H;
g = real(ifft2(Hgh.*y));
subplot(439);
imshow(uint8(abs(g)));
title('Filtered Image');
subplot(4,3,10);
imshow(Hgh,[]);
title('Gaussian Highpass Filter');
x = fft2(double(D<=D0));
n = 2;
D0 = 20;
u = 0:(M-1);
v = 0:(N-1);
idx = find(u>M/2);
u(idx) = u(idx)-M;
idy = find(v>N/2);
v(idy) = v(idy)-N;
[V U] = meshgrid(v,u);
D = sqrt(U.^2+V.^2);
H = 1./(1+(D./D0).^(2.*n));
d = H.*x;
g = real(ifft2(double(d)));
subplot(4,3,11);
imshow(uint8(abs(g)));
title('Butterworth Lowpass');